### ISSUE TITLE
Mraa ISR time-out in Python

### ISSUE THREAD

**Issue by BTWS** [intel-iot-devkit/mraa#492] opened 2016-04-13 08:04 UTC
Is similar functionality possible like [pulseIn on Arduino](https://www.arduino.cc/en/Reference/PulseIn)? 

`pulseIn(pin, value, timeout)`

I wan't to use an interrupt but with a **time-out** of a given amount, let's say 0.5 seconds.

Relevant:
[gpio-interrupt-isr](http://iotdk.intel.com/docs/master/mraa/python/example.html#gpio-interrupt-isr)
[hello_isr.py](https://github.com/intel-iot-devkit/mraa/blob/master/examples/python/hello_isr.py)

**Comment by arfoll** [comment] 2016-04-13 08:07
No there's nothing like this, the problem is that we're on Linux so you simply can't make assumptions about timings this way.

**Comment by alext-mkrs** [comment] 2016-05-09 18:41
As long as @arfoll has provided an answer, I'm closing this one

**Closed by alext-mkrs** 2016-05-09 18:41 UTC
Labels: question
