### ISSUE TITLE
Yocto build fails with JavaScript enabled

### ISSUE THREAD

**Issue by whbruce** [intel-iot-devkit/mraa#485] opened 2016-03-28 21:56 UTC
I am adding mraa to a Yocto build using recipes from intel-iot-middleware layer. This has been working for me (with a bbapend to support builds later than 0.9.6), but with version 0.10.1 I get the following error in do_package_qa
`
ERROR: QA Issue: package mraa contains bad RPATH /path/to/build/tmp/work/core2-32-poky-linux/mraa/0.10.1-r1/build/src in file /path/to/build/tmp/work/core2-32-poky-linux/mraa/0.10.1-r1/packages-split/mraa/usr/lib/node_modules/mraa/mraa.node [rpaths]
`

I can see why this is happening by looking at the log.do_compile. You can see that I am targeting Edison, but I would expect the same behavior with any target.
`/path/to/build/tmp/sysroots/x86_64-linux/usr/bin/i586-poky-linux/i586-poky-linux-g++  -fPIC  -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=/path/to/build/tmp/sysroots/edison  -O2 -pipe -g -feliminate-unused-debug-types -fvisibility-inlines-hidden  -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -shared  -o mraa.node CMakeFiles/mraajs.dir/mraajsJAVASCRIPT_wrap.cxx.o ../libmraa.so.0.10.1 -lpthread -ldl -Wl,-rpath,/path/to/build/tmp/work/core2-32-poky-linux/mraa/0.10.1-r1/build/src 
`

Swig and/or cmake is somehow causing insertion of an RPATH. I don't want to skip QA tests. Does anyone know how to fix this cleanly?

**Comment by xbolshe** [comment] 2016-03-28 22:10
I use -DCMAKE_SKIP_RPATH=TRUE to fix this problem.

**Comment by xbolshe** [comment] 2016-03-28 22:11
https://cmake.org/cmake/help/v3.0/variable/CMAKE_SKIP_RPATH.html

**Comment by Propanu** [comment] 2016-03-28 22:58
Opened #486 to fix this.

**Comment by whbruce** [comment] 2016-03-28 23:00
Thanks @xbolshe. @Propanu's PR uses set_target_properties to set CMAKE_SKIP_RPATH=TRUE. I did a manual fix and it resolved build failure for me.

**Comment by Propanu** [comment] 2016-03-31 23:37
Turns out skipping RPATHs entirely will break linking for the Python bindings. Will have to find a better solution.

**Comment by petreeftime** [comment] 2016-04-06 09:40
Python package is installed in /usr/lib/python2.7/site-packages/ instead of /usr/lib64/python2.7/site-packages/ for me, might be related to this issue.

**Comment by xbolshe** [comment] 2016-04-06 20:26
@Propanu It is strange. I have no problem with Node nor Python with Galileo and Edison boards.
What recipes do you use? What kind of linking problem do you have? What board do you use?

**Comment by Propanu** [comment] 2016-04-26 18:20
@xbolshe with RPATHs off and a custom install dir that is not on LD's path, you'll get a linker error when you try to load MRAA from Node or Python. This is also caused by the fact we went from static to dynamic with our loading our bindings to avoid multiple init calls. What's interesting though is that RPATHs are supposed to be off by default but Yocto builds clearly say otherwise. It does help to have an RPATH added to the binaries, when installing in a non-system folder, but instead of adding the build source path (which is temporary for Yocto builds) we want to add the install path and location of the .so. Thus I think one of the other options [in here](https://cmake.org/Wiki/CMake_RPATH_handling#Default_RPATH_settings) will do the trick.

**Comment by sandeep-mvd** [comment] 2016-11-18 09:46
I see the same error when trying to update mraa to 1.5.1
I am working on edison as well.
@Propanu The issue you opened #486 is closed. In 1.5.1 mraa both the patches are present. But still I see this error.
Is there any working workaround?

**Comment by arfoll** [comment] 2016-11-18 12:58
Try applying this patch 7cade840122cb1a45d7aa178a7ad80d4174ae0bf

**Comment by arfoll** [comment] 2016-11-18 13:25
new patch - d6f53f92cedcc6d5b240bedebe8f2766c0f06679

**Comment by sandeep-mvd** [comment] 2016-11-22 08:16
Thank you @arfoll 
It solves the problem.

**Comment by alext-mkrs** [comment] 2016-11-23 11:00
This one seems to be resolved now, @arfoll, @whbruce, do you think it can be closed?

**Comment by arfoll** [comment] 2016-11-23 11:49
not yet, patch is in a branch, I need to merge it into master.

**Comment by arfoll** [comment] 2016-11-23 18:00
Merged, thanks!

**Closed by arfoll** 2016-11-23 18:00 UTC
Labels: enhancement
