### ISSUE TITLE
mraa pin no.9 is invalid GPIO pin?

### ISSUE THREAD

**Issue by coloz** [intel-iot-devkit/mraa#258] opened 2015-08-22 03:34 UTC
i seen the breakout board's mraa number,i want to use no.9
but error said, 'Invalid GPIO pin specified'

**Comment by alext-mkrs** [comment] 2015-08-22 17:02
Are you talking about mini-breakout or an Arduino breakout board here?

A reproducer program listing woud also help a lot in troubleshooting this.

**Comment by coloz** [comment] 2015-08-24 05:21
import mraa
x = mraa.Gpio(9)

it is 'Invalid GPIO pin specified'

i try to use C/C++, it's same error

**Comment by arfoll** [comment] 2015-08-24 09:25
Can you tell us which board, what OS and mraa version (mraa.getVersion() will tell you) and maybe the output of syslog? There's some doc on doing so here: https://github.com/intel-iot-devkit/mraa/blob/master/docs/debugging.md

Without any of this there's not much anyone can do.

**Comment by alext-mkrs** [comment] 2015-09-03 17:55
@coloz is this still actual? If yes, please provide the information @arfoll and I have requested above - that will help us to troubleshoot it. Other wise, please let us know and we'll close this one.

**Comment by alext-mkrs** [comment] 2015-09-20 15:35
@arfoll looks like this one is no longer active, propose closing it.

**Comment by coloz** [comment] 2015-10-06 06:53
@arfoll  breakout board & Release 2.1 Yocto* complete image,thanks a lot

**Comment by alext-mkrs** [comment] 2015-10-06 18:41
@coloz you still haven't provided any useful debug information. "breakout board" is too generic, which one do you use, can you provide e.g. a link to the web shop, if you don't know what the name is? On both Arduino break out board and mini-breakout board gpio pin number 9 is valid, so you shouldn't be getting such an error there, so I suspect you have something else.

Image version is also useless, because it's the library version that matters.

Please see the document @arfoll referred to: https://github.com/intel-iot-devkit/mraa/blob/master/docs/debugging.md and execute commands listed there (to get library version and gather logs), then show us the output.

**Comment by alext-mkrs** [comment] 2015-10-26 20:47
Ok, it's been long enough with no activity - I'm closing this one. @coloz, feel free to add a comment if you still need help with this one.

**Closed by alext-mkrs** 2015-10-26 20:47 UTC
Labels: help wanted
